server:
  port: 8080

logging:
  level:
    com: debug
    org.hibernate.type: trace

spring:
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500