spring:
  profiles:
    active: local
    include:
      - const
      - db
      - security
      - jwt
      - ssl

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
